

export function hexToRgb(hex) {
    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : null;
  }

  //test only
export const testVisitedCountries = ['Greece', 'Cyprus', 'Turkey', 'Serbia', 'Bulgaria', 'Italy', 'North Macedonia',
  'Germany', 'Poland', 'France', 'Netherlands', 'Hungary', 'Austria', 'Lithuania', 'Sweden', 'Spain'];

export var data = [
    { 'Country': 'Afghanistan', 'Alpha2': 'AF', 'Alpha3': 'AFG', 'Numeric': '4', 'Lat': '33', 'Lon': '65', 'en': false },
{ 'Country': 'Albania', 'Alpha2': 'AL', 'Alpha3': 'ALB', 'Numeric': '8', 'Lat': '41', 'Lon': '20', 'en': false },
{ 'Country': 'Algeria', 'Alpha2': 'DZ', 'Alpha3': 'DZA', 'Numeric': '12', 'Lat': '28', 'Lon': '3', 'en': false },
{ 'Country': 'American Samoa', 'Alpha2': 'AS', 'Alpha3': 'ASM', 'Numeric': '16', 'Lat': '-14.3333', 'Lon': '-170', 'en': false },
{ 'Country': 'Andorra', 'Alpha2': 'AD', 'Alpha3': 'AND', 'Numeric': '20', 'Lat': '42.5', 'Lon': '1.6', 'en': false },
{ 'Country': 'Angola', 'Alpha2': 'AO', 'Alpha3': 'AGO', 'Numeric': '24', 'Lat': '-12.5', 'Lon': '18.5', 'en': false },
{ 'Country': 'Anguilla', 'Alpha2': 'AI', 'Alpha3': 'AIA', 'Numeric': '660', 'Lat': '18.25', 'Lon': '-63.1667', 'en': false },
{ 'Country': 'Antarctica', 'Alpha2': 'AQ', 'Alpha3': 'ATA', 'Numeric': '10', 'Lat': '-90', 'Lon': '0', 'en': false },
{ 'Country': 'Antigua and Barbuda', 'Alpha2': 'AG', 'Alpha3': 'ATG', 'Numeric': '28', 'Lat': '17.05', 'Lon': '-61.8', 'en': false },
{ 'Country': 'Argentina', 'Alpha2': 'AR', 'Alpha3': 'ARG', 'Numeric': '32', 'Lat': '-34', 'Lon': '-64', 'en': false },
{ 'Country': 'Armenia', 'Alpha2': 'AM', 'Alpha3': 'ARM', 'Numeric': '51', 'Lat': '40', 'Lon': '45', 'en': false },
{ 'Country': 'Aruba', 'Alpha2': 'AW', 'Alpha3': 'ABW', 'Numeric': '533', 'Lat': '12.5', 'Lon': '-69.9667', 'en': false },
{ 'Country': 'Australia', 'Alpha2': 'AU', 'Alpha3': 'AUS', 'Numeric': '36', 'Lat': '-27', 'Lon': '133', 'en': false },
{ 'Country': 'Austria', 'Alpha2': 'AT', 'Alpha3': 'AUT', 'Numeric': '40', 'Lat': '47.3333', 'Lon': '13.3333', 'en': false },
{ 'Country': 'Azerbaijan', 'Alpha2': 'AZ', 'Alpha3': 'AZE', 'Numeric': '31', 'Lat': '40.5', 'Lon': '47.5', 'en': false },
{ 'Country': 'Bahamas', 'Alpha2': 'BS', 'Alpha3': 'BHS', 'Numeric': '44', 'Lat': '24.25', 'Lon': '-76', 'en': false },
{ 'Country': 'Bahrain', 'Alpha2': 'BH', 'Alpha3': 'BHR', 'Numeric': '48', 'Lat': '26', 'Lon': '50.55', 'en': false },
{ 'Country': 'Bangladesh', 'Alpha2': 'BD', 'Alpha3': 'BGD', 'Numeric': '50', 'Lat': '24', 'Lon': '90', 'en': false },
{ 'Country': 'Barbados', 'Alpha2': 'BB', 'Alpha3': 'BRB', 'Numeric': '52', 'Lat': '13.1667', 'Lon': '-59.5333', 'en': false },
{ 'Country': 'Belarus', 'Alpha2': 'BY', 'Alpha3': 'BLR', 'Numeric': '112', 'Lat': '53', 'Lon': '28', 'en': false },
{ 'Country': 'Belgium', 'Alpha2': 'BE', 'Alpha3': 'BEL', 'Numeric': '56', 'Lat': '50.8333', 'Lon': '4', 'en': false },
{ 'Country': 'Belize', 'Alpha2': 'BZ', 'Alpha3': 'BLZ', 'Numeric': '84', 'Lat': '17.25', 'Lon': '-88.75', 'en': false },
{ 'Country': 'Benin', 'Alpha2': 'BJ', 'Alpha3': 'BEN', 'Numeric': '204', 'Lat': '9.5', 'Lon': '2.25', 'en': false },
{ 'Country': 'Bermuda', 'Alpha2': 'BM', 'Alpha3': 'BMU', 'Numeric': '60', 'Lat': '32.3333', 'Lon': '-64.75', 'en': false },
{ 'Country': 'Bhutan', 'Alpha2': 'BT', 'Alpha3': 'BTN', 'Numeric': '64', 'Lat': '27.5', 'Lon': '90.5', 'en': false },
{ 'Country': 'Bolivia, Plurinational State of', 'Alpha2': 'BO', 'Alpha3': 'BOL', 'Numeric': '68', 'Lat': '-17', 'Lon': '-65', 'en': false },
{ 'Country': 'Bolivia', 'Alpha2': 'BO', 'Alpha3': 'BOL', 'Numeric': '68', 'Lat': '-17', 'Lon': '-65', 'en': false },
{ 'Country': 'Bosnia and Herzegovina', 'Alpha2': 'BA', 'Alpha3': 'BIH', 'Numeric': '70', 'Lat': '44', 'Lon': '18', 'en': false },
{ 'Country': 'Botswana', 'Alpha2': 'BW', 'Alpha3': 'BWA', 'Numeric': '72', 'Lat': '-22', 'Lon': '24', 'en': false },
{ 'Country': 'Bouvet Island', 'Alpha2': 'BV', 'Alpha3': 'BVT', 'Numeric': '74', 'Lat': '-54.4333', 'Lon': '3.4', 'en': false },
{ 'Country': 'Brazil', 'Alpha2': 'BR', 'Alpha3': 'BRA', 'Numeric': '76', 'Lat': '-10', 'Lon': '-55', 'en': false },
{ 'Country': 'British Indian Ocean Territory', 'Alpha2': 'IO', 'Alpha3': 'IOT', 'Numeric': '86', 'Lat': '-6', 'Lon': '71.5', 'en': false },
{ 'Country': 'Brunei Darussalam', 'Alpha2': 'BN', 'Alpha3': 'BRN', 'Numeric': '96', 'Lat': '4.5', 'Lon': '114.6667', 'en': false },
{ 'Country': 'Brunei', 'Alpha2': 'BN', 'Alpha3': 'BRN', 'Numeric': '96', 'Lat': '4.5', 'Lon': '114.6667', 'en': false },
{ 'Country': 'Bulgaria', 'Alpha2': 'BG', 'Alpha3': 'BGR', 'Numeric': '100', 'Lat': '43', 'Lon': '25', 'en': false },
{ 'Country': 'Burkina Faso', 'Alpha2': 'BF', 'Alpha3': 'BFA', 'Numeric': '854', 'Lat': '13', 'Lon': '-2', 'en': false },
{ 'Country': 'Burundi', 'Alpha2': 'BI', 'Alpha3': 'BDI', 'Numeric': '108', 'Lat': '-3.5', 'Lon': '30', 'en': false },
{ 'Country': 'Cambodia', 'Alpha2': 'KH', 'Alpha3': 'KHM', 'Numeric': '116', 'Lat': '13', 'Lon': '105', 'en': false },
{ 'Country': 'Cameroon', 'Alpha2': 'CM', 'Alpha3': 'CMR', 'Numeric': '120', 'Lat': '6', 'Lon': '12', 'en': false },
{ 'Country': 'Canada', 'Alpha2': 'CA', 'Alpha3': 'CAN', 'Numeric': '124', 'Lat': '60', 'Lon': '-95', 'en': false },
{ 'Country': 'Cape Verde', 'Alpha2': 'CV', 'Alpha3': 'CPV', 'Numeric': '132', 'Lat': '16', 'Lon': '-24', 'en': false },
{ 'Country': 'Cayman Islands', 'Alpha2': 'KY', 'Alpha3': 'CYM', 'Numeric': '136', 'Lat': '19.5', 'Lon': '-80.5', 'en': false },
{ 'Country': 'Central African Republic', 'Alpha2': 'CF', 'Alpha3': 'CAF', 'Numeric': '140', 'Lat': '7', 'Lon': '21', 'en': false },
{ 'Country': 'Chad', 'Alpha2': 'TD', 'Alpha3': 'TCD', 'Numeric': '148', 'Lat': '15', 'Lon': '19', 'en': false },
{ 'Country': 'Chile', 'Alpha2': 'CL', 'Alpha3': 'CHL', 'Numeric': '152', 'Lat': '-30', 'Lon': '-71', 'en': false },
{ 'Country': 'China', 'Alpha2': 'CN', 'Alpha3': 'CHN', 'Numeric': '156', 'Lat': '35', 'Lon': '105', 'en': false },
{ 'Country': 'Christmas Island', 'Alpha2': 'CX', 'Alpha3': 'CXR', 'Numeric': '162', 'Lat': '-10.5', 'Lon': '105.6667', 'en': false },
{ 'Country': 'Cocos (Keeling) Islands', 'Alpha2': 'CC', 'Alpha3': 'CCK', 'Numeric': '166', 'Lat': '-12.5', 'Lon': '96.8333', 'en': false },
{ 'Country': 'Colombia', 'Alpha2': 'CO', 'Alpha3': 'COL', 'Numeric': '170', 'Lat': '4', 'Lon': '-72', 'en': false },
{ 'Country': 'Comoros', 'Alpha2': 'KM', 'Alpha3': 'COM', 'Numeric': '174', 'Lat': '-12.1667', 'Lon': '44.25', 'en': false },
{ 'Country': 'Congo', 'Alpha2': 'CG', 'Alpha3': 'COG', 'Numeric': '178', 'Lat': '-1', 'Lon': '15', 'en': false },
{ 'Country': 'Congo, the Democratic Republic of the', 'Alpha2': 'CD', 'Alpha3': 'COD', 'Numeric': '180', 'Lat': '0', 'Lon': '25', 'en': false },
{ 'Country': 'Cook Islands', 'Alpha2': 'CK', 'Alpha3': 'COK', 'Numeric': '184', 'Lat': '-21.2333', 'Lon': '-159.7667', 'en': false },
{ 'Country': 'Costa Rica', 'Alpha2': 'CR', 'Alpha3': 'CRI', 'Numeric': '188', 'Lat': '10', 'Lon': '-84', 'en': false },
{ 'Country': 'Côte d\'Ivoire', 'Alpha2': 'CI', 'Alpha3': 'CIV', 'Numeric': '384', 'Lat': '8', 'Lon': '-5', 'en': false },
{ 'Country': 'Ivory Coast', 'Alpha2': 'CI', 'Alpha3': 'CIV', 'Numeric': '384', 'Lat': '8', 'Lon': '-5', 'en': false },
{ 'Country': 'Croatia', 'Alpha2': 'HR', 'Alpha3': 'HRV', 'Numeric': '191', 'Lat': '45.1667', 'Lon': '15.5', 'en': false },
{ 'Country': 'Cuba', 'Alpha2': 'CU', 'Alpha3': 'CUB', 'Numeric': '192', 'Lat': '21.5', 'Lon': '-80', 'en': false },
{ 'Country': 'Cyprus', 'Alpha2': 'CY', 'Alpha3': 'CYP', 'Numeric': '196', 'Lat': '35', 'Lon': '33', 'en': false },
{ 'Country': 'Czech Republic', 'Alpha2': 'CZ', 'Alpha3': 'CZE', 'Numeric': '203', 'Lat': '49.75', 'Lon': '15.5', 'en': false },
{ 'Country': 'Denmark', 'Alpha2': 'DK', 'Alpha3': 'DNK', 'Numeric': '208', 'Lat': '56', 'Lon': '10', 'en': false },
{ 'Country': 'Djibouti', 'Alpha2': 'DJ', 'Alpha3': 'DJI', 'Numeric': '262', 'Lat': '11.5', 'Lon': '43', 'en': false },
{ 'Country': 'Dominica', 'Alpha2': 'DM', 'Alpha3': 'DMA', 'Numeric': '212', 'Lat': '15.4167', 'Lon': '-61.3333', 'en': false },
{ 'Country': 'Dominican Republic', 'Alpha2': 'DO', 'Alpha3': 'DOM', 'Numeric': '214', 'Lat': '19', 'Lon': '-70.6667', 'en': false },
{ 'Country': 'Ecuador', 'Alpha2': 'EC', 'Alpha3': 'ECU', 'Numeric': '218', 'Lat': '-2', 'Lon': '-77.5', 'en': false },
{ 'Country': 'Egypt', 'Alpha2': 'EG', 'Alpha3': 'EGY', 'Numeric': '818', 'Lat': '27', 'Lon': '30', 'en': false },
{ 'Country': 'El Salvador', 'Alpha2': 'SV', 'Alpha3': 'SLV', 'Numeric': '222', 'Lat': '13.8333', 'Lon': '-88.9167', 'en': false },
{ 'Country': 'Equatorial Guinea', 'Alpha2': 'GQ', 'Alpha3': 'GNQ', 'Numeric': '226', 'Lat': '2', 'Lon': '10', 'en': false },
{ 'Country': 'Eritrea', 'Alpha2': 'ER', 'Alpha3': 'ERI', 'Numeric': '232', 'Lat': '15', 'Lon': '39', 'en': false },
{ 'Country': 'Estonia', 'Alpha2': 'EE', 'Alpha3': 'EST', 'Numeric': '233', 'Lat': '59', 'Lon': '26', 'en': false },
{ 'Country': 'Ethiopia', 'Alpha2': 'ET', 'Alpha3': 'ETH', 'Numeric': '231', 'Lat': '8', 'Lon': '38', 'en': false },
{ 'Country': 'Falkland Islands (Malvinas)', 'Alpha2': 'FK', 'Alpha3': 'FLK', 'Numeric': '238', 'Lat': '-51.75', 'Lon': '-59', 'en': false },
{ 'Country': 'Faroe Islands', 'Alpha2': 'FO', 'Alpha3': 'FRO', 'Numeric': '234', 'Lat': '62', 'Lon': '-7', 'en': false },
{ 'Country': 'Fiji', 'Alpha2': 'FJ', 'Alpha3': 'FJI', 'Numeric': '242', 'Lat': '-18', 'Lon': '175', 'en': false },
{ 'Country': 'Finland', 'Alpha2': 'FI', 'Alpha3': 'FIN', 'Numeric': '246', 'Lat': '64', 'Lon': '26', 'en': false },
{ 'Country': 'France', 'Alpha2': 'FR', 'Alpha3': 'FRA', 'Numeric': '250', 'Lat': '46', 'Lon': '2', 'en': false },
{ 'Country': 'French Guiana', 'Alpha2': 'GF', 'Alpha3': 'GUF', 'Numeric': '254', 'Lat': '4', 'Lon': '-53', 'en': false },
{ 'Country': 'French Polynesia', 'Alpha2': 'PF', 'Alpha3': 'PYF', 'Numeric': '258', 'Lat': '-15', 'Lon': '-140', 'en': false },
{ 'Country': 'French Southern Territories', 'Alpha2': 'TF', 'Alpha3': 'ATF', 'Numeric': '260', 'Lat': '-43', 'Lon': '67', 'en': false },
{ 'Country': 'Gabon', 'Alpha2': 'GA', 'Alpha3': 'GAB', 'Numeric': '266', 'Lat': '-1', 'Lon': '11.75', 'en': false },
{ 'Country': 'Gambia', 'Alpha2': 'GM', 'Alpha3': 'GMB', 'Numeric': '270', 'Lat': '13.4667', 'Lon': '-16.5667', 'en': false },
{ 'Country': 'Georgia', 'Alpha2': 'GE', 'Alpha3': 'GEO', 'Numeric': '268', 'Lat': '42', 'Lon': '43.5', 'en': false },
{ 'Country': 'Germany', 'Alpha2': 'DE', 'Alpha3': 'DEU', 'Numeric': '276', 'Lat': '51', 'Lon': '9', 'en': false },
{ 'Country': 'Ghana', 'Alpha2': 'GH', 'Alpha3': 'GHA', 'Numeric': '288', 'Lat': '8', 'Lon': '-2', 'en': false },
{ 'Country': 'Gibraltar', 'Alpha2': 'GI', 'Alpha3': 'GIB', 'Numeric': '292', 'Lat': '36.1833', 'Lon': '-5.3667', 'en': false },
{ 'Country': 'Greece', 'Alpha2': 'GR', 'Alpha3': 'GRC', 'Numeric': '300', 'Lat': '39', 'Lon': '22', 'en': false },
{ 'Country': 'Greenland', 'Alpha2': 'GL', 'Alpha3': 'GRL', 'Numeric': '304', 'Lat': '72', 'Lon': '-40', 'en': false },
{ 'Country': 'Grenada', 'Alpha2': 'GD', 'Alpha3': 'GRD', 'Numeric': '308', 'Lat': '12.1167', 'Lon': '-61.6667', 'en': false },
{ 'Country': 'Guadeloupe', 'Alpha2': 'GP', 'Alpha3': 'GLP', 'Numeric': '312', 'Lat': '16.25', 'Lon': '-61.5833', 'en': false },
{ 'Country': 'Guam', 'Alpha2': 'GU', 'Alpha3': 'GUM', 'Numeric': '316', 'Lat': '13.4667', 'Lon': '144.7833', 'en': false },
{ 'Country': 'Guatemala', 'Alpha2': 'GT', 'Alpha3': 'GTM', 'Numeric': '320', 'Lat': '15.5', 'Lon': '-90.25', 'en': false },
{ 'Country': 'Guernsey', 'Alpha2': 'GG', 'Alpha3': 'GGY', 'Numeric': '831', 'Lat': '49.5', 'Lon': '-2.56', 'en': false },
{ 'Country': 'Guinea', 'Alpha2': 'GN', 'Alpha3': 'GIN', 'Numeric': '324', 'Lat': '11', 'Lon': '-10', 'en': false },
{ 'Country': 'Guinea-Bissau', 'Alpha2': 'GW', 'Alpha3': 'GNB', 'Numeric': '624', 'Lat': '12', 'Lon': '-15', 'en': false },
{ 'Country': 'Guyana', 'Alpha2': 'GY', 'Alpha3': 'GUY', 'Numeric': '328', 'Lat': '5', 'Lon': '-59', 'en': false },
{ 'Country': 'Haiti', 'Alpha2': 'HT', 'Alpha3': 'HTI', 'Numeric': '332', 'Lat': '19', 'Lon': '-72.4167', 'en': false },
{ 'Country': 'Heard Island and McDonald Islands', 'Alpha2': 'HM', 'Alpha3': 'HMD', 'Numeric': '334', 'Lat': '-53.1', 'Lon': '72.5167', 'en': false },
{ 'Country': 'Holy See (Vatican City State)', 'Alpha2': 'VA', 'Alpha3': 'VAT', 'Numeric': '336', 'Lat': '41.9', 'Lon': '12.45', 'en': false },
{ 'Country': 'Honduras', 'Alpha2': 'HN', 'Alpha3': 'HND', 'Numeric': '340', 'Lat': '15', 'Lon': '-86.5', 'en': false },
{ 'Country': 'Hong Kong', 'Alpha2': 'HK', 'Alpha3': 'HKG', 'Numeric': '344', 'Lat': '22.25', 'Lon': '114.1667', 'en': false },
{ 'Country': 'Hungary', 'Alpha2': 'HU', 'Alpha3': 'HUN', 'Numeric': '348', 'Lat': '47', 'Lon': '20', 'en': false },
{ 'Country': 'Iceland', 'Alpha2': 'IS', 'Alpha3': 'ISL', 'Numeric': '352', 'Lat': '65', 'Lon': '-18', 'en': false },
{ 'Country': 'India', 'Alpha2': 'IN', 'Alpha3': 'IND', 'Numeric': '356', 'Lat': '20', 'Lon': '77', 'en': false },
{ 'Country': 'Indonesia', 'Alpha2': 'ID', 'Alpha3': 'IDN', 'Numeric': '360', 'Lat': '-5', 'Lon': '120', 'en': false },
{ 'Country': 'Iran, Islamic Republic of', 'Alpha2': 'IR', 'Alpha3': 'IRN', 'Numeric': '364', 'Lat': '32', 'Lon': '53', 'en': false },
{ 'Country': 'Iraq', 'Alpha2': 'IQ', 'Alpha3': 'IRQ', 'Numeric': '368', 'Lat': '33', 'Lon': '44', 'en': false },
{ 'Country': 'Ireland', 'Alpha2': 'IE', 'Alpha3': 'IRL', 'Numeric': '372', 'Lat': '53', 'Lon': '-8', 'en': false },
{ 'Country': 'Isle of Man', 'Alpha2': 'IM', 'Alpha3': 'IMN', 'Numeric': '833', 'Lat': '54.23', 'Lon': '-4.55', 'en': false },
{ 'Country': 'Israel', 'Alpha2': 'IL', 'Alpha3': 'ISR', 'Numeric': '376', 'Lat': '31.5', 'Lon': '34.75', 'en': false },
{ 'Country': 'Italy', 'Alpha2': 'IT', 'Alpha3': 'ITA', 'Numeric': '380', 'Lat': '42.8333', 'Lon': '12.8333', 'en': false },
{ 'Country': 'Jamaica', 'Alpha2': 'JM', 'Alpha3': 'JAM', 'Numeric': '388', 'Lat': '18.25', 'Lon': '-77.5', 'en': false },
{ 'Country': 'Japan', 'Alpha2': 'JP', 'Alpha3': 'JPN', 'Numeric': '392', 'Lat': '36', 'Lon': '138', 'en': false },
{ 'Country': 'Jersey', 'Alpha2': 'JE', 'Alpha3': 'JEY', 'Numeric': '832', 'Lat': '49.21', 'Lon': '-2.13', 'en': false },
{ 'Country': 'Jordan', 'Alpha2': 'JO', 'Alpha3': 'JOR', 'Numeric': '400', 'Lat': '31', 'Lon': '36', 'en': false },
{ 'Country': 'Kazakhstan', 'Alpha2': 'KZ', 'Alpha3': 'KAZ', 'Numeric': '398', 'Lat': '48', 'Lon': '68', 'en': false },
{ 'Country': 'Kenya', 'Alpha2': 'KE', 'Alpha3': 'KEN', 'Numeric': '404', 'Lat': '1', 'Lon': '38', 'en': false },
{ 'Country': 'Kiribati', 'Alpha2': 'KI', 'Alpha3': 'KIR', 'Numeric': '296', 'Lat': '1.4167', 'Lon': '173', 'en': false },
{ 'Country': 'Korea, Democratic People\'s Republic of', 'Alpha2': 'KP', 'Alpha3': 'PRK', 'Numeric': '408', 'Lat': '40', 'Lon': '127', 'en': false },
{ 'Country': 'Korea, Republic of', 'Alpha2': 'KR', 'Alpha3': 'KOR', 'Numeric': '410', 'Lat': '37', 'Lon': '127.5', 'en': false },
{ 'Country': 'South Korea', 'Alpha2': 'KR', 'Alpha3': 'KOR', 'Numeric': '410', 'Lat': '37', 'Lon': '127.5', 'en': false },
{ 'Country': 'Kuwait', 'Alpha2': 'KW', 'Alpha3': 'KWT', 'Numeric': '414', 'Lat': '29.3375', 'Lon': '47.6581', 'en': false },
{ 'Country': 'Kyrgyzstan', 'Alpha2': 'KG', 'Alpha3': 'KGZ', 'Numeric': '417', 'Lat': '41', 'Lon': '75', 'en': false },
{ 'Country': 'Lao People\'s Democratic Republic', 'Alpha2': 'LA', 'Alpha3': 'LAO', 'Numeric': '418', 'Lat': '18', 'Lon': '105', 'en': false },
{ 'Country': 'Latvia', 'Alpha2': 'LV', 'Alpha3': 'LVA', 'Numeric': '428', 'Lat': '57', 'Lon': '25', 'en': false },
{ 'Country': 'Lebanon', 'Alpha2': 'LB', 'Alpha3': 'LBN', 'Numeric': '422', 'Lat': '33.8333', 'Lon': '35.8333', 'en': false },
{ 'Country': 'Lesotho', 'Alpha2': 'LS', 'Alpha3': 'LSO', 'Numeric': '426', 'Lat': '-29.5', 'Lon': '28.5', 'en': false },
{ 'Country': 'Liberia', 'Alpha2': 'LR', 'Alpha3': 'LBR', 'Numeric': '430', 'Lat': '6.5', 'Lon': '-9.5', 'en': false },
{ 'Country': 'Libyan Arab Jamahiriya', 'Alpha2': 'LY', 'Alpha3': 'LBY', 'Numeric': '434', 'Lat': '25', 'Lon': '17', 'en': false },
{ 'Country': 'Libya', 'Alpha2': 'LY', 'Alpha3': 'LBY', 'Numeric': '434', 'Lat': '25', 'Lon': '17', 'en': false },
{ 'Country': 'Liechtenstein', 'Alpha2': 'LI', 'Alpha3': 'LIE', 'Numeric': '438', 'Lat': '47.1667', 'Lon': '9.5333', 'en': false },
{ 'Country': 'Lithuania', 'Alpha2': 'LT', 'Alpha3': 'LTU', 'Numeric': '440', 'Lat': '56', 'Lon': '24', 'en': false },
{ 'Country': 'Luxembourg', 'Alpha2': 'LU', 'Alpha3': 'LUX', 'Numeric': '442', 'Lat': '49.75', 'Lon': '6.1667', 'en': false },
{ 'Country': 'Macao', 'Alpha2': 'MO', 'Alpha3': 'MAC', 'Numeric': '446', 'Lat': '22.1667', 'Lon': '113.55', 'en': false },
{ 'Country': 'North Macedonia', 'Alpha2': 'MK', 'Alpha3': 'MKD', 'Numeric': '807', 'Lat': '41.8333', 'Lon': '22', 'en': false },
{ 'Country': 'Madagascar', 'Alpha2': 'MG', 'Alpha3': 'MDG', 'Numeric': '450', 'Lat': '-20', 'Lon': '47', 'en': false },
{ 'Country': 'Malawi', 'Alpha2': 'MW', 'Alpha3': 'MWI', 'Numeric': '454', 'Lat': '-13.5', 'Lon': '34', 'en': false },
{ 'Country': 'Malaysia', 'Alpha2': 'MY', 'Alpha3': 'MYS', 'Numeric': '458', 'Lat': '2.5', 'Lon': '112.5', 'en': false },
{ 'Country': 'Maldives', 'Alpha2': 'MV', 'Alpha3': 'MDV', 'Numeric': '462', 'Lat': '3.25', 'Lon': '73', 'en': false },
{ 'Country': 'Mali', 'Alpha2': 'ML', 'Alpha3': 'MLI', 'Numeric': '466', 'Lat': '17', 'Lon': '-4', 'en': false },
{ 'Country': 'Malta', 'Alpha2': 'MT', 'Alpha3': 'MLT', 'Numeric': '470', 'Lat': '35.8333', 'Lon': '14.5833', 'en': false },
{ 'Country': 'Marshall Islands', 'Alpha2': 'MH', 'Alpha3': 'MHL', 'Numeric': '584', 'Lat': '9', 'Lon': '168', 'en': false },
{ 'Country': 'Martinique', 'Alpha2': 'MQ', 'Alpha3': 'MTQ', 'Numeric': '474', 'Lat': '14.6667', 'Lon': '-61', 'en': false },
{ 'Country': 'Mauritania', 'Alpha2': 'MR', 'Alpha3': 'MRT', 'Numeric': '478', 'Lat': '20', 'Lon': '-12', 'en': false },
{ 'Country': 'Mauritius', 'Alpha2': 'MU', 'Alpha3': 'MUS', 'Numeric': '480', 'Lat': '-20.2833', 'Lon': '57.55', 'en': false },
{ 'Country': 'Mayotte', 'Alpha2': 'YT', 'Alpha3': 'MYT', 'Numeric': '175', 'Lat': '-12.8333', 'Lon': '45.1667', 'en': false },
{ 'Country': 'Mexico', 'Alpha2': 'MX', 'Alpha3': 'MEX', 'Numeric': '484', 'Lat': '23', 'Lon': '-102', 'en': false },
{ 'Country': 'Micronesia, Federated States of', 'Alpha2': 'FM', 'Alpha3': 'FSM', 'Numeric': '583', 'Lat': '6.9167', 'Lon': '158.25', 'en': false },
{ 'Country': 'Moldova, Republic of', 'Alpha2': 'MD', 'Alpha3': 'MDA', 'Numeric': '498', 'Lat': '47', 'Lon': '29', 'en': false },
{ 'Country': 'Monaco', 'Alpha2': 'MC', 'Alpha3': 'MCO', 'Numeric': '492', 'Lat': '43.7333', 'Lon': '7.4', 'en': false },
{ 'Country': 'Mongolia', 'Alpha2': 'MN', 'Alpha3': 'MNG', 'Numeric': '496', 'Lat': '46', 'Lon': '105', 'en': false },
{ 'Country': 'Montenegro', 'Alpha2': 'ME', 'Alpha3': 'MNE', 'Numeric': '499', 'Lat': '42', 'Lon': '19', 'en': false },
{ 'Country': 'Montserrat', 'Alpha2': 'MS', 'Alpha3': 'MSR', 'Numeric': '500', 'Lat': '16.75', 'Lon': '-62.2', 'en': false },
{ 'Country': 'Morocco', 'Alpha2': 'MA', 'Alpha3': 'MAR', 'Numeric': '504', 'Lat': '32', 'Lon': '-5', 'en': false },
{ 'Country': 'Mozambique', 'Alpha2': 'MZ', 'Alpha3': 'MOZ', 'Numeric': '508', 'Lat': '-18.25', 'Lon': '35', 'en': false },
{ 'Country': 'Myanmar', 'Alpha2': 'MM', 'Alpha3': 'MMR', 'Numeric': '104', 'Lat': '22', 'Lon': '98', 'en': false },
{ 'Country': 'Burma', 'Alpha2': 'MM', 'Alpha3': 'MMR', 'Numeric': '104', 'Lat': '22', 'Lon': '98', 'en': false },
{ 'Country': 'Namibia', 'Alpha2': 'NA', 'Alpha3': 'NAM', 'Numeric': '516', 'Lat': '-22', 'Lon': '17', 'en': false },
{ 'Country': 'Nauru', 'Alpha2': 'NR', 'Alpha3': 'NRU', 'Numeric': '520', 'Lat': '-0.5333', 'Lon': '166.9167', 'en': false },
{ 'Country': 'Nepal', 'Alpha2': 'NP', 'Alpha3': 'NPL', 'Numeric': '524', 'Lat': '28', 'Lon': '84', 'en': false },
{ 'Country': 'Netherlands', 'Alpha2': 'NL', 'Alpha3': 'NLD', 'Numeric': '528', 'Lat': '52.5', 'Lon': '5.75', 'en': false },
{ 'Country': 'Netherlands Antilles', 'Alpha2': 'AN', 'Alpha3': 'ANT', 'Numeric': '530', 'Lat': '12.25', 'Lon': '-68.75', 'en': false },
{ 'Country': 'New Caledonia', 'Alpha2': 'NC', 'Alpha3': 'NCL', 'Numeric': '540', 'Lat': '-21.5', 'Lon': '165.5', 'en': false },
{ 'Country': 'New Zealand', 'Alpha2': 'NZ', 'Alpha3': 'NZL', 'Numeric': '554', 'Lat': '-41', 'Lon': '174', 'en': false },
{ 'Country': 'Nicaragua', 'Alpha2': 'NI', 'Alpha3': 'NIC', 'Numeric': '558', 'Lat': '13', 'Lon': '-85', 'en': false },
{ 'Country': 'Niger', 'Alpha2': 'NE', 'Alpha3': 'NER', 'Numeric': '562', 'Lat': '16', 'Lon': '8', 'en': false },
{ 'Country': 'Nigeria', 'Alpha2': 'NG', 'Alpha3': 'NGA', 'Numeric': '566', 'Lat': '10', 'Lon': '8', 'en': false },
{ 'Country': 'Niue', 'Alpha2': 'NU', 'Alpha3': 'NIU', 'Numeric': '570', 'Lat': '-19.0333', 'Lon': '-169.8667', 'en': false },
{ 'Country': 'Norfolk Island', 'Alpha2': 'NF', 'Alpha3': 'NFK', 'Numeric': '574', 'Lat': '-29.0333', 'Lon': '167.95', 'en': false },
{ 'Country': 'Northern Mariana Islands', 'Alpha2': 'MP', 'Alpha3': 'MNP', 'Numeric': '580', 'Lat': '15.2', 'Lon': '145.75', 'en': false },
{ 'Country': 'Norway', 'Alpha2': 'NO', 'Alpha3': 'NOR', 'Numeric': '578', 'Lat': '62', 'Lon': '10', 'en': false },
{ 'Country': 'Oman', 'Alpha2': 'OM', 'Alpha3': 'OMN', 'Numeric': '512', 'Lat': '21', 'Lon': '57', 'en': false },
{ 'Country': 'Pakistan', 'Alpha2': 'PK', 'Alpha3': 'PAK', 'Numeric': '586', 'Lat': '30', 'Lon': '70', 'en': false },
{ 'Country': 'Palau', 'Alpha2': 'PW', 'Alpha3': 'PLW', 'Numeric': '585', 'Lat': '7.5', 'Lon': '134.5', 'en': false },
{ 'Country': 'Palestinian Territory, Occupied', 'Alpha2': 'PS', 'Alpha3': 'PSE', 'Numeric': '275', 'Lat': '32', 'Lon': '35.25', 'en': false },
{ 'Country': 'Panama', 'Alpha2': 'PA', 'Alpha3': 'PAN', 'Numeric': '591', 'Lat': '9', 'Lon': '-80', 'en': false },
{ 'Country': 'Papua New Guinea', 'Alpha2': 'PG', 'Alpha3': 'PNG', 'Numeric': '598', 'Lat': '-6', 'Lon': '147', 'en': false },
{ 'Country': 'Paraguay', 'Alpha2': 'PY', 'Alpha3': 'PRY', 'Numeric': '600', 'Lat': '-23', 'Lon': '-58', 'en': false },
{ 'Country': 'Peru', 'Alpha2': 'PE', 'Alpha3': 'PER', 'Numeric': '604', 'Lat': '-10', 'Lon': '-76', 'en': false },
{ 'Country': 'Philippines', 'Alpha2': 'PH', 'Alpha3': 'PHL', 'Numeric': '608', 'Lat': '13', 'Lon': '122', 'en': false },
{ 'Country': 'Pitcairn', 'Alpha2': 'PN', 'Alpha3': 'PCN', 'Numeric': '612', 'Lat': '-24.7', 'Lon': '-127.4', 'en': false },
{ 'Country': 'Poland', 'Alpha2': 'PL', 'Alpha3': 'POL', 'Numeric': '616', 'Lat': '52', 'Lon': '20', 'en': false },
{ 'Country': 'Portugal', 'Alpha2': 'PT', 'Alpha3': 'PRT', 'Numeric': '620', 'Lat': '39.5', 'Lon': '-8', 'en': false },
{ 'Country': 'Puerto Rico', 'Alpha2': 'PR', 'Alpha3': 'PRI', 'Numeric': '630', 'Lat': '18.25', 'Lon': '-66.5', 'en': false },
{ 'Country': 'Qatar', 'Alpha2': 'QA', 'Alpha3': 'QAT', 'Numeric': '634', 'Lat': '25.5', 'Lon': '51.25', 'en': false },
{ 'Country': 'Réunion', 'Alpha2': 'RE', 'Alpha3': 'REU', 'Numeric': '638', 'Lat': '-21.1', 'Lon': '55.6', 'en': false },
{ 'Country': 'Romania', 'Alpha2': 'RO', 'Alpha3': 'ROU', 'Numeric': '642', 'Lat': '46', 'Lon': '25', 'en': false },
{ 'Country': 'Russian Federation', 'Alpha2': 'RU', 'Alpha3': 'RUS', 'Numeric': '643', 'Lat': '60', 'Lon': '100', 'en': false },
{ 'Country': 'Russia', 'Alpha2': 'RU', 'Alpha3': 'RUS', 'Numeric': '643', 'Lat': '60', 'Lon': '100', 'en': false },
{ 'Country': 'Rwanda', 'Alpha2': 'RW', 'Alpha3': 'RWA', 'Numeric': '646', 'Lat': '-2', 'Lon': '30', 'en': false },
{ 'Country': 'Saint Helena, Ascension and Tristan da Cunha', 'Alpha2': 'SH', 'Alpha3': 'SHN', 'Numeric': '654', 'Lat': '-15.9333', 'Lon': '-5.7', 'en': false },
{ 'Country': 'Saint Kitts and Nevis', 'Alpha2': 'KN', 'Alpha3': 'KNA', 'Numeric': '659', 'Lat': '17.3333', 'Lon': '-62.75', 'en': false },
{ 'Country': 'Saint Lucia', 'Alpha2': 'LC', 'Alpha3': 'LCA', 'Numeric': '662', 'Lat': '13.8833', 'Lon': '-61.1333', 'en': false },
{ 'Country': 'Saint Pierre and Miquelon', 'Alpha2': 'PM', 'Alpha3': 'SPM', 'Numeric': '666', 'Lat': '46.8333', 'Lon': '-56.3333', 'en': false },
{ 'Country': 'Saint Vincent and the Grenadines', 'Alpha2': 'VC', 'Alpha3': 'VCT', 'Numeric': '670', 'Lat': '13.25', 'Lon': '-61.2', 'en': false },
{ 'Country': 'Saint Vincent & the Grenadines', 'Alpha2': 'VC', 'Alpha3': 'VCT', 'Numeric': '670', 'Lat': '13.25', 'Lon': '-61.2', 'en': false },
{ 'Country': 'St. Vincent and the Grenadines', 'Alpha2': 'VC', 'Alpha3': 'VCT', 'Numeric': '670', 'Lat': '13.25', 'Lon': '-61.2', 'en': false },
{ 'Country': 'Samoa', 'Alpha2': 'WS', 'Alpha3': 'WSM', 'Numeric': '882', 'Lat': '-13.5833', 'Lon': '-172.3333', 'en': false },
{ 'Country': 'San Marino', 'Alpha2': 'SM', 'Alpha3': 'SMR', 'Numeric': '674', 'Lat': '43.7667', 'Lon': '12.4167', 'en': false },
{ 'Country': 'Sao Tome and Principe', 'Alpha2': 'ST', 'Alpha3': 'STP', 'Numeric': '678', 'Lat': '1', 'Lon': '7', 'en': false },
{ 'Country': 'Saudi Arabia', 'Alpha2': 'SA', 'Alpha3': 'SAU', 'Numeric': '682', 'Lat': '25', 'Lon': '45', 'en': false },
{ 'Country': 'Senegal', 'Alpha2': 'SN', 'Alpha3': 'SEN', 'Numeric': '686', 'Lat': '14', 'Lon': '-14', 'en': false },
{ 'Country': 'Serbia', 'Alpha2': 'RS', 'Alpha3': 'SRB', 'Numeric': '688', 'Lat': '44', 'Lon': '21', 'en': false },
{ 'Country': 'Seychelles', 'Alpha2': 'SC', 'Alpha3': 'SYC', 'Numeric': '690', 'Lat': '-4.5833', 'Lon': '55.6667', 'en': false },
{ 'Country': 'Sierra Leone', 'Alpha2': 'SL', 'Alpha3': 'SLE', 'Numeric': '694', 'Lat': '8.5', 'Lon': '-11.5', 'en': false },
{ 'Country': 'Singapore', 'Alpha2': 'SG', 'Alpha3': 'SGP', 'Numeric': '702', 'Lat': '1.3667', 'Lon': '103.8', 'en': false },
{ 'Country': 'Slovakia', 'Alpha2': 'SK', 'Alpha3': 'SVK', 'Numeric': '703', 'Lat': '48.6667', 'Lon': '19.5', 'en': false },
{ 'Country': 'Slovenia', 'Alpha2': 'SI', 'Alpha3': 'SVN', 'Numeric': '705', 'Lat': '46', 'Lon': '15', 'en': false },
{ 'Country': 'Solomon Islands', 'Alpha2': 'SB', 'Alpha3': 'SLB', 'Numeric': '90', 'Lat': '-8', 'Lon': '159', 'en': false },
{ 'Country': 'Somalia', 'Alpha2': 'SO', 'Alpha3': 'SOM', 'Numeric': '706', 'Lat': '10', 'Lon': '49', 'en': false },
{ 'Country': 'South Africa', 'Alpha2': 'ZA', 'Alpha3': 'ZAF', 'Numeric': '710', 'Lat': '-29', 'Lon': '24', 'en': false },
{ 'Country': 'South Georgia and the South Sandwich Islands', 'Alpha2': 'GS', 'Alpha3': 'SGS', 'Numeric': '239', 'Lat': '-54.5', 'Lon': '-37', 'en': false },
{ 'Country': 'South Sudan', 'Alpha2': 'SS', 'Alpha3': 'SSD', 'Numeric': '728', 'Lat': '8', 'Lon': '30', 'en': false },
{ 'Country': 'Spain', 'Alpha2': 'ES', 'Alpha3': 'ESP', 'Numeric': '724', 'Lat': '40', 'Lon': '-4', 'en': false },
{ 'Country': 'Sri Lanka', 'Alpha2': 'LK', 'Alpha3': 'LKA', 'Numeric': '144', 'Lat': '7', 'Lon': '81', 'en': false },
{ 'Country': 'Sudan', 'Alpha2': 'SD', 'Alpha3': 'SDN', 'Numeric': '736', 'Lat': '15', 'Lon': '30', 'en': false },
{ 'Country': 'Suriname', 'Alpha2': 'SR', 'Alpha3': 'SUR', 'Numeric': '740', 'Lat': '4', 'Lon': '-56', 'en': false },
{ 'Country': 'Svalbard and Jan Mayen', 'Alpha2': 'SJ', 'Alpha3': 'SJM', 'Numeric': '744', 'Lat': '78', 'Lon': '20', 'en': false },
{ 'Country': 'Swaziland', 'Alpha2': 'SZ', 'Alpha3': 'SWZ', 'Numeric': '748', 'Lat': '-26.5', 'Lon': '31.5', 'en': false },
{ 'Country': 'Sweden', 'Alpha2': 'SE', 'Alpha3': 'SWE', 'Numeric': '752', 'Lat': '62', 'Lon': '15', 'en': false },
{ 'Country': 'Switzerland', 'Alpha2': 'CH', 'Alpha3': 'CHE', 'Numeric': '756', 'Lat': '47', 'Lon': '8', 'en': false },
{ 'Country': 'Syrian Arab Republic', 'Alpha2': 'SY', 'Alpha3': 'SYR', 'Numeric': '760', 'Lat': '35', 'Lon': '38', 'en': false },
{ 'Country': 'Taiwan, Province of China', 'Alpha2': 'TW', 'Alpha3': 'TWN', 'Numeric': '158', 'Lat': '23.5', 'Lon': '121', 'en': false },
{ 'Country': 'Taiwan', 'Alpha2': 'TW', 'Alpha3': 'TWN', 'Numeric': '158', 'Lat': '23.5', 'Lon': '121', 'en': false },
{ 'Country': 'Tajikistan', 'Alpha2': 'TJ', 'Alpha3': 'TJK', 'Numeric': '762', 'Lat': '39', 'Lon': '71', 'en': false },
{ 'Country': 'Tanzania, United Republic of', 'Alpha2': 'TZ', 'Alpha3': 'TZA', 'Numeric': '834', 'Lat': '-6', 'Lon': '35', 'en': false },
{ 'Country': 'Thailand', 'Alpha2': 'TH', 'Alpha3': 'THA', 'Numeric': '764', 'Lat': '15', 'Lon': '100', 'en': false },
{ 'Country': 'Timor-Leste', 'Alpha2': 'TL', 'Alpha3': 'TLS', 'Numeric': '626', 'Lat': '-8.55', 'Lon': '125.5167', 'en': false },
{ 'Country': 'Togo', 'Alpha2': 'TG', 'Alpha3': 'TGO', 'Numeric': '768', 'Lat': '8', 'Lon': '1.1667', 'en': false },
{ 'Country': 'Tokelau', 'Alpha2': 'TK', 'Alpha3': 'TKL', 'Numeric': '772', 'Lat': '-9', 'Lon': '-172', 'en': false },
{ 'Country': 'Tonga', 'Alpha2': 'TO', 'Alpha3': 'TON', 'Numeric': '776', 'Lat': '-20', 'Lon': '-175', 'en': false },
{ 'Country': 'Trinidad and Tobago', 'Alpha2': 'TT', 'Alpha3': 'TTO', 'Numeric': '780', 'Lat': '11', 'Lon': '-61', 'en': false },
{ 'Country': 'Tunisia', 'Alpha2': 'TN', 'Alpha3': 'TUN', 'Numeric': '788', 'Lat': '34', 'Lon': '9', 'en': false },
{ 'Country': 'Turkey', 'Alpha2': 'TR', 'Alpha3': 'TUR', 'Numeric': '792', 'Lat': '39', 'Lon': '35', 'en': false },
{ 'Country': 'Turkmenistan', 'Alpha2': 'TM', 'Alpha3': 'TKM', 'Numeric': '795', 'Lat': '40', 'Lon': '60', 'en': false },
{ 'Country': 'Turks and Caicos Islands', 'Alpha2': 'TC', 'Alpha3': 'TCA', 'Numeric': '796', 'Lat': '21.75', 'Lon': '-71.5833', 'en': false },
{ 'Country': 'Tuvalu', 'Alpha2': 'TV', 'Alpha3': 'TUV', 'Numeric': '798', 'Lat': '-8', 'Lon': '178', 'en': false },
{ 'Country': 'Uganda', 'Alpha2': 'UG', 'Alpha3': 'UGA', 'Numeric': '800', 'Lat': '1', 'Lon': '32', 'en': false },
{ 'Country': 'Ukraine', 'Alpha2': 'UA', 'Alpha3': 'UKR', 'Numeric': '804', 'Lat': '49', 'Lon': '32', 'en': false },
{ 'Country': 'United Arab Emirates', 'Alpha2': 'AE', 'Alpha3': 'ARE', 'Numeric': '784', 'Lat': '24', 'Lon': '54', 'en': false },
{ 'Country': 'United Kingdom', 'Alpha2': 'GB', 'Alpha3': 'GBR', 'Numeric': '826', 'Lat': '54', 'Lon': '-2', 'en': false },
{ 'Country': 'United States', 'Alpha2': 'US', 'Alpha3': 'USA', 'Numeric': '840', 'Lat': '38', 'Lon': '-97', 'en': false },
{ 'Country': 'United States Minor Outlying Islands', 'Alpha2': 'UM', 'Alpha3': 'UMI', 'Numeric': '581', 'Lat': '19.2833', 'Lon': '166.6', 'en': false },
{ 'Country': 'Uruguay', 'Alpha2': 'UY', 'Alpha3': 'URY', 'Numeric': '858', 'Lat': '-33', 'Lon': '-56', 'en': false },
{ 'Country': 'Uzbekistan', 'Alpha2': 'UZ', 'Alpha3': 'UZB', 'Numeric': '860', 'Lat': '41', 'Lon': '64', 'en': false },
{ 'Country': 'Vanuatu', 'Alpha2': 'VU', 'Alpha3': 'VUT', 'Numeric': '548', 'Lat': '-16', 'Lon': '167', 'en': false },
{ 'Country': 'Venezuela, Bolivarian Republic of', 'Alpha2': 'VE', 'Alpha3': 'VEN', 'Numeric': '862', 'Lat': '8', 'Lon': '-66', 'en': false },
{ 'Country': 'Venezuela', 'Alpha2': 'VE', 'Alpha3': 'VEN', 'Numeric': '862', 'Lat': '8', 'Lon': '-66', 'en': false },
{ 'Country': 'Viet Nam', 'Alpha2': 'VN', 'Alpha3': 'VNM', 'Numeric': '704', 'Lat': '16', 'Lon': '106', 'en': false },
{ 'Country': 'Vietnam', 'Alpha2': 'VN', 'Alpha3': 'VNM', 'Numeric': '704', 'Lat': '16', 'Lon': '106', 'en': false },
{ 'Country': 'Virgin Islands, British', 'Alpha2': 'VG', 'Alpha3': 'VGB', 'Numeric': '92', 'Lat': '18.5', 'Lon': '-64.5', 'en': false },
{ 'Country': 'Virgin Islands, U.S.', 'Alpha2': 'VI', 'Alpha3': 'VIR', 'Numeric': '850', 'Lat': '18.3333', 'Lon': '-64.8333', 'en': false },
{ 'Country': 'Wallis and Futuna', 'Alpha2': 'WF', 'Alpha3': 'WLF', 'Numeric': '876', 'Lat': '-13.3', 'Lon': '-176.2', 'en': false },
{ 'Country': 'Western Sahara', 'Alpha2': 'EH', 'Alpha3': 'ESH', 'Numeric': '732', 'Lat': '24.5', 'Lon': '-13', 'en': false },
{ 'Country': 'Yemen', 'Alpha2': 'YE', 'Alpha3': 'YEM', 'Numeric': '887', 'Lat': '15', 'Lon': '48', 'en': false },
{ 'Country': 'Zambia', 'Alpha2': 'ZM', 'Alpha3': 'ZMB', 'Numeric': '894', 'Lat': '-15', 'Lon': '30', 'en': false },
{ 'Country': 'Zimbabwe', 'Alpha2': 'ZW', 'Alpha3': 'ZWE', 'Numeric': '716', 'Lat': '-20', 'Lon': '30', 'en': false }
  ]

